name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: Tazlin/pyinstaller-action-windows@python3-10-11-pyinstaller-6.3.0
      with:
        path: worker

    - uses: actions/upload-artifact@v2
      with:
        name: worker-exe
        path: worker/dist/entry_point

